app:
  bot: # discord bot setup
    token: ""
    client secret: ""
  DM: 
    forward: # forward private messages to channel
      - 1029306511663975487
  on_message_delete: # send deleted message to guild channel
    1020269242061123066: # guild id
      - 1021236086008257170 # channel id
  chatgpt: # chatgpt chatbot channel
    temperature: [0.8, 1.2] # number or [min, max]
    channel:
      - 1092365663408594763
    icon: "https://cdn.discordapp.com/**.webp"
  command: # bot commmand
    help:
      message: |
        Help message
    report: 
      forward: # bug report to channel
        - 1029306511663975487
    reload:
      permission: # allowed user id
        - 1025037519630347687
  event:
    goodnight:
      channel:
        - 1038160548800835188
      message: '@everyone'

# module: chatgpt
chatgpt: 
  token: ""
  max_tokens: 500

# module: games
games:
  chance: [0.20, 0.81] # [min, max]
  fortune:
    key: ["大吉", "吉", "小吉", "尚可", "小兇", "兇", "大凶"]
    sep: [0, 0.05, 0.15, 0.35, 0.65, 0.85, 0.95, 1]
