app:
  bot: # discord bot setup
    token: ""
    client secret: ""
  DM: 
    forward: # forward private messages to channel
      - 1029306511663975487
  on_message_delete: # send deleted message to guild channel
    1020269242061123066: # guild id
      - 1021236086008257170 # channel id
  on_guild_emojis_update: # send emoji updates to guild channel
    1020269242061123066: # guild id
      - 1021236086008257170 # channel id
  on_guild_stickers_update: # send sticker updates to guild channel
    1020269242061123066: # guild id
      - 1021236086008257170 # channel id
  chatgpt: # chatgpt chatbot channel
    temperature: [0.8, 1.2] # number or [min, max]
    channel:
      - 1092365663408594763
    icon: "https://cdn.discordapp.com/**.webp"
  command: # bot commmand
    help:
      message: |
        Help message
    chance: [0.25, 0.75]
    fortune:
      key: ["大吉", "吉", "小吉", "尚可", "小兇", "兇", "大凶"]
      ratio: [0.05, 0.1, 0.2, 0.3, 0.2, 0.1, 0.05]    
    report: 
      forward: # bug report to channel
        - 1029306511663975487
    reload:
      permission: # allowed user id
        - 1025037519630347687
  event:
    goodnight:
      channel:
        - 1038160548800835188
      message: '@everyone'

# module: chatgpt
chatgpt: 
  token: ""
  max_tokens: 500
